# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KnowlegeWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        self.bottomWidget.setGeometry(QtCore.QRect(60, 540, 771, 41))
        self.bottomWidget.setStyleSheet("background-color: rgb(109, 255, 93);")
        self.bottomWidget.setObjectName("bottomWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.bottomWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 10, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.bindPhone = MyLabel(self.bottomWidget)
        self.bindPhone.setObjectName("bindPhone")
        self.gridLayout.addWidget(self.bindPhone, 0, 7, 1, 1)
        self.regOrLogin = MyLabel(self.bottomWidget)
        self.regOrLogin.setObjectName("regOrLogin")
        self.gridLayout.addWidget(self.regOrLogin, 0, 5, 1, 1)
        self.bindWechat = MyLabel(self.bottomWidget)
        self.bindWechat.setObjectName("bindWechat")
        self.gridLayout.addWidget(self.bindWechat, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(205, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 8, 1, 1)
        self.addKnowlege = MyLabel(self.bottomWidget)
        self.addKnowlege.setObjectName("addKnowlege")
        self.gridLayout.addWidget(self.addKnowlege, 0, 9, 1, 1)
        self.versionInfo = QtWidgets.QLabel(self.bottomWidget)
        self.versionInfo.setObjectName("versionInfo")
        self.gridLayout.addWidget(self.versionInfo, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 6, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(8, 1)
        self.middleWidget = QtWidgets.QWidget(self.centralwidget)
        self.middleWidget.setGeometry(QtCore.QRect(130, 190, 571, 61))
        self.middleWidget.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.middleWidget.setObjectName("middleWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.middleWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.searchText = QtWidgets.QLineEdit(self.middleWidget)
        self.searchText.setObjectName("searchText")
        self.gridLayout_2.addWidget(self.searchText, 0, 0, 1, 1)
        self.searchBtn = MyLabel(self.middleWidget)
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout_2.addWidget(self.searchBtn, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        self.topWidget.setGeometry(QtCore.QRect(40, 20, 801, 41))
        self.topWidget.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.topWidget.setObjectName("topWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.topWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 7, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 5, 1, 1)
        self.orgLogo = MyLabel(self.topWidget)
        self.orgLogo.setObjectName("orgLogo")
        self.gridLayout_3.addWidget(self.orgLogo, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(540, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 3, 1, 1)
        self.hiddenLab = MyLabel(self.topWidget)
        self.hiddenLab.setObjectName("hiddenLab")
        self.gridLayout_3.addWidget(self.hiddenLab, 0, 4, 1, 1)
        self.closeLab = MyLabel(self.topWidget)
        self.closeLab.setObjectName("closeLab")
        self.gridLayout_3.addWidget(self.closeLab, 0, 6, 1, 1)
        self.titleName = QtWidgets.QLabel(self.topWidget)
        self.titleName.setObjectName("titleName")
        self.gridLayout_3.addWidget(self.titleName, 0, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.org_logo = MyLabel(self.centralwidget)
        self.org_logo.setGeometry(QtCore.QRect(370, 140, 54, 12))
        self.org_logo.setObjectName("org_logo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bindPhone.setText(_translate("MainWindow", "TextLabel"))
        self.regOrLogin.setText(_translate("MainWindow", "TextLabel"))
        self.bindWechat.setText(_translate("MainWindow", "TextLabel"))
        self.addKnowlege.setText(_translate("MainWindow", "TextLabel"))
        self.versionInfo.setText(_translate("MainWindow", "TextLabel"))
        self.searchBtn.setText(_translate("MainWindow", "TextLabel"))
        self.orgLogo.setText(_translate("MainWindow", "TextLabel"))
        self.hiddenLab.setText(_translate("MainWindow", "TextLabel"))
        self.closeLab.setText(_translate("MainWindow", "TextLabel"))
        self.titleName.setText(_translate("MainWindow", "TextLabel"))
        self.org_logo.setText(_translate("MainWindow", "TextLabel"))

from mylabel import MyLabel
